spring:
  application:
    name: ProductService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 4000

jwt.expiration: 3600000
jwt.secret: "YXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2Rm"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%X{correlationId}] - %msg%n"

rate-limit:
  auth:
    capacity: 3
    refill-amount: 3
    refill-duration-minutes: 1
  general:
    capacity: 20
    refill-amount: 20
    refill-duration-minutes: 1